# -*- coding: utf-8 -*-
"""KPK dari 3 dan 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwzPTUO9i_vcuixpd-0F9T81v3MuCRtC
"""

def bilangan(a, b):

    b = max(a, b)
    kpk = b

    while True:
        if kpk % a == 0 and kpk % b == 0:
            return kpk
        kpk += b

a = 3
b = 4

print("KPK dari", a, "dan", b, "adalah", bilangan(a, b))
