# -*- coding: utf-8 -*-
"""Fungsi untuk menukar 2 variabel x dan y.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3fPRYK7x9IahlosHWFHX_ztv3kKEaby
"""

x = 'manggis'
y = 'pisang'
z = None

print(f"Piring 1: {x}")
print(f"Piring 2: {y}")
print(f"Piring 3: {z}\n")

step = 0
while step < 3:
    if step == 0:
        z = x
        x = None
        print(f"Piring 1: {x}")
        print(f"Piring 2: {y}")
        print(f"Piring 3: {z}\n")

    elif step == 1:
        x = y
        y = None
        print(f"Piring 1: {x}")
        print(f"Piring 2: {y}")
        print(f"Piring 3: {z}\n")

    elif step == 2:
        y = z
        z = None
        print(f"Piring 1: {x}")
        print(f"Piring 2: {y}")
        print(f"Piring 3: {z}\n")

    step += 1
