# -*- coding: utf-8 -*-
"""Menghitung Luas Segitiga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0TMrB2hgNCxaX0lOnduk8KUWBpo-3vu
"""

alas = 25
tinggi = 30
print(f"Suatu segitiga memiliki alas sepanjang {alas} dan tinggi sepanjang {tinggi}")

luas = alas * tinggi / 2

print(f"Luas dari Segitiga tersebut adalah {luas}")