# -*- coding: utf-8 -*-
"""Menghitung Luas Jajar Genjang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfM4--UcZXphQRnZMS6ACrs1sX5v9H-d
"""

panjang = 5
tinggi = 3

print(f"Suatu jajar genjang memiliki panjang sepanjang {panjang} dan tinggi sepanjang {tinggi}")

luas = panjang * tinggi

print(f"Luas dari jajar genjang tersebut adalah {luas}")