# -*- coding: utf-8 -*-
"""Menghitung Volume Tabung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186U8bPsetvmJnNCJgT_f1EEz_2yVU6Zo
"""

import numpy as np
jari = 3
tinggi = 5

print(f"Suatu tabung memiliki jari-jari sepanjang {jari} dan tinggi sepanjang {tinggi}")

luas = np.pi * jari * jari * tinggi

print(f"Luas dari tabung tersebut adalah {luas}")