# -*- coding: utf-8 -*-
"""Menghitung Volume Kerucut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cHzfn-60y_6YDBJqV3eAJ0kS_dxexPv
"""

import numpy as np
diameter = 5
tinggi = 4

print(f"Suatu kerucut memiliki diameter sepanjang {diameter} dan tinggi sepanjang {tinggi}")
jari = diameter / 2
print(f"Jari-jarinya adalah {diameter} / 2 = {jari}")
luas = np.pi * jari * jari * tinggi / 3

print(f"Luas dari tabung tersebut adalah {luas}")