# -*- coding: utf-8 -*-
"""Fungsi untuk menukar 2 variabel x dan y.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3fPRYK7x9IahlosHWFHX_ztv3kKEaby
"""

piring1 = 'manggis'
piring2 = 'pisang'
piring3 = None

print(f"Piring 1: {piring1}")
print(f"Piring 2: {piring2}")
print(f"Piring 3: {piring3}\n")

step = 0
while step < 3:
    if step == 0:
        piring3 = piring1
        piring1 = None
        print(f"Piring 1: {piring1}")
        print(f"Piring 2: {piring2}")
        print(f"Piring 3: {piring3}\n")

    elif step == 1:
        piring1 = piring2
        piring2 = None
        print(f"Piring 1: {piring1}")
        print(f"Piring 2: {piring2}")
        print(f"Piring 3: {piring3}\n")

    elif step == 2:
        piring2 = piring3
        piring3 = None
        print(f"Piring 1: {piring1}")
        print(f"Piring 2: {piring2}")
        print(f"Piring 3: {piring3}\n")

    step += 1